#!/bin/bash

read -p "Are you sure you want to do this? This rewrites history for this repository: (Y or N) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	echo
  echo "Well, that's settled, then"
  exit 1
fi

echo
echo
read -p "Just want to make sure, do you really want to do this? Rewriting history is no small task. (Y or N) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	echo
  echo "See, I thought not"
  exit 1
fi

echo
echo
read -p "Search within yourself, is this something you really want to do? The repo as you know it will never be the same! (Y or N) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	echo
	echo "That was close, the repo is saved!"
  exit 1
fi

echo
echo
echo "History is being rewritten. May God have mercy on your soul"

for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
    git branch --track ${branch##*/} $branch
done


git filter-branch --tag-name-filter cat --index-filter "git rm -r --cached --ignore-unmatch $@" --prune-empty -f -- --all

rm -rf .git/refs/original/

git reflog expire --expire=now --all

git gc --prune=now

git gc --aggressive --prune=now
